### ISSUE TITLE
As an admin, I want to have the Handsfree.js sandbox as a "hero unit"

### ISSUE THREAD

**Issue by labofoz** [BrowseHandsfree/handsfree-discourse-hero#1]
## Scope
- [ ] I see the Handsfree.js sandbox when I visit browsehandsfree.com
- [ ] The cursor and any active demo works for the parent site too
- [ ] Get the `npm run embed` output from Handsfree.js to embed with discourse with minimal editing

## Tasks
- [ ] Setup README with instructions on syncing a theme with discourse (maybe use discourse-outrun)
